name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: tejasdgangurde  # Replace with your GitHub username
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist/github-contribution-grid-snake.svg
      - name: Push to GitHub
        uses: actions/checkout@v3
      - name: Commit and Push
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Updated contribution snake graph"
          git push
